CREATE DATABASE VETERINARIA;
CREATE TABLE ENDERECOS (
ID_ENDERECOS INT PRIMARY KEY AUTO_INCREMENT,
CEP VARCHAR(11) NOT NULL,
RUA VARCHAR(22),
COMPLEMENTO VARCHAR(45),
NUMERO INT(2),
ID_PESSOA INT NOT NULL,
FOREIGN key (ID_PESSOA) REFERENCES PESSOA (ID_PESSOA));

CREATE TABLE PESSOA(
Id_pessoa INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(40) NOT NULL,
idade INT(2) NOT NULL,
CPF VARCHAR(11) NOT NULL,
telefone INT(12));

CREATE TABLE TUTOR(
 id_tutor INT PRIMARY KEY AUTO_INCREMENT,
  situacao char(1) NOT NULL,
  fidelidade VARCHAR(45) NOT NULL,
  obs VARCHAR(50),
 ID_PESSOA INT NOT NULL,
 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID_PESSOA));
 
 CREATE TABLE VETERINARIO(
 id_veterinario INT PRIMARY KEY AUTO_INCREMENT,
 CRMV VARCHAR(45) NOT NULL,
 ESPECIALIDADE VARCHAR(10) NOT NULL,
 SALARIO INT(10.2) NOT NULL,
 ID_PESSOA INT NOT NULL,
 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID_PESSOA));
 
 CREATE TABLE ANIMAL(
 id_animal INT PRIMARY KEY AUTO_INCREMENT,
 nome VARCHAR(10) NOT NULL,
 idade INT(2) NOT NULL,
 porte CHAR(1) NOT NULL,
 PESO INT(2) NOT NULL,
 SITUAÇAO CHAR(1) NOT NULL,
 OBS VARCHAR(40),
 ID_TUTOR INT NOT NULL,
FOREIGN key (ID_TUTOR) REFERENCES TUTOR (ID_TUTOR));
 
 CREATE TABLE CONSULTA(
 ID_CONSULTA INT PRIMARY KEY AUTO_INCREMENT,
 DATA DATE NOT NULL,
 TIPO VARCHAR(10) NOT NULL,
 OBS VARCHAR(45),
 SITUIAÇAO CHAR(1) NOT NULL,
 ID_ANIMAL INT NOT NULL,
FOREIGN key (ID_ANIMAL) REFERENCES ANIMAL (ID_ANIMAL),
ID_VETERINARIO INT NOT NULL,
FOREIGN key (ID_VETERINARIO) REFERENCES VETERINARIO (ID_VETERINARIO));
 
 
 CREATE TABLE RECEITA(
 ID_RECEITA INT PRIMARY KEY AUTO_INCREMENT,
 MEDICAMENTO VARCHAR(20) NOT NULL,
 DIAS INT(2) NOT NULL,
 TRATAMENTO VARCHAR(150),
 DATA_INICIO DATE NOT NULL,
 DATA_FIM DATE NOT NULL,
 OBS VARCHAR(150),
 ID_CONSULTA INT NOT NULL,
 FOREIGN key (ID_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA));
 
 CREATE TABLE HISTORICO(
 ID_HISTORICO INT PRIMARY KEY AUTO_INCREMENT,
 OBS VARCHAR(300),
 ID_CONSULTA INT NOT NULL,
FOREIGN key (ID_CONSULTA) REFERENCES CONSULTA (ID_CONSULTA));


insert into pessoa(nome,cpf,idade,situacao,telefone)
values 
("yan","78945618751",12,'o',217784956),
("douglas","78945548751",22,'f',217745656),
("gabriel","78945549167",28,'o',217745631),
("ruan","71348249167",25,'o',211876131),
("betania","78913468167",35,'o',412845631),
("fabricio","78919752017",17,'o',412845648);
select *from  pessoa;
SELECT * FROM VETERINARIO;
insert into veterinario(CRMV,ESPECIALIDADE,SALARIO,ID_PESSOA)
VALUES
("VET4555","CIRURGIÃO",9000.00,6),
("VET2209","ANESTESISTA",9500.00,5);
SELECT * FROM TUTOR;
INSERT INTO TUTOR(SITUACAO,FIDELIDADE,OBS,ID_PESSOA)
VALUES 
('O',"FIEL","CLIENTE EXIGENTE",1),
('O',"INFIEL","CLIENTE CHATO",2),
('O',"FIEL","CLIENTE NOVO(NAO ENTENDE DOS TRATAMENTOS)",3),
('O',"FIEL","CLIENTE NOVO(NAO ENTENDE DOS TRATAMENTOS)",3),
('O',"INFIEL","CLIENTE ANTIGO",4);

INSERT INTO ANIMAL (NOME,IDADE,PORTE,PESO,SITUAÇAO,OBS,ID_TUTOR)
VALUES
("PRINCESA",3,'M',24,"D","CAO OBESO",3),
("BETOVEM",4,'P',15,"D","CAO CEGO",4);
SELECT * FROM CONSULTA;
INSERT INTO CONSULTA(DATA,TIPO,OBS,SITUAÇAO,ID_ANIMAL,ID_VETERINARIO)
VALUES 
('2024-02-25','CHECKUP','CAO IDOSO','O',2,4),
('2024-02-15','RAIOX','GATO DEFICIENTE DA PATA DIANTEIRA','O',1,3);
SELECT * FROM CONSULTA;
INSERT INTO HISTORICO(OBS,ID_CONSULTA)
VALUES
("CAO SADIO, APRESENTA CANSAÇO POR VELHICE",3),
("GATO APRESENTA DIFICULDADES PARA SE ADPATAR A NOVA PROTESE DA PATA DIANTEIRA",4);